// C++ side of the CXX bridge.
//
// The header `bridge.h` is auto-generated by cxx-build from the
// `#[cxx::bridge]` block in src/lib.rs. DO NOT EDIT — re-run cargo build
// to regenerate it.
//
// To add a new function:
//   1. Declare it in the `extern "C++"` block in src/lib.rs
//   2. Implement it here with the same signature
//   3. cargo build

#include "cpp/bridge.h"
#include <string>

namespace rust_cxx_app_template {

std::string greet_from_cpp(const std::string& name) {
    return "Hello, " + name + ", from C++!";
}

}  // namespace rust_cxx_app_template
