//! rust_cxx_app template — Rust + CXX FFI.
//!
//! The CXX bridge is defined in this module. Add `extern "Rust"` and
//! `extern "C++"` blocks here. The matching C++ implementation goes in
//! `cpp/bridge.cc` and the corresponding header in `cpp/bridge.h` is
//! auto-generated by cxx-build.

#[cxx::bridge]
mod ffi {
    // ── Shared types (visible on both sides) ──────────────────────────
    struct Point3 {
        x: f64,
        y: f64,
        z: f64,
    }

    // ── Rust → C++ (Rust calls into C++) ──────────────────────────────
    extern "C++" {
        include!("cpp/bridge.h");
        fn greet_from_cpp(name: &str) -> String;
    }

    // ── C++ → Rust (C++ calls into Rust) ──────────────────────────────
    extern "Rust" {
        fn mean_rust(values: &[f64]) -> f64;
        fn sum_rust(values: &[f64]) -> f64;
    }
}

// ── Rust implementations (callable from C++) ────────────────────────

/// Mean of a slice. Returns 0.0 for an empty slice.
pub fn mean_rust(values: &[f64]) -> f64 {
    if values.is_empty() {
        log::warn!("mean_rust called on empty slice");
        return 0.0;
    }
    values.iter().sum::<f64>() / values.len() as f64
}

/// Sum of a slice. Returns 0.0 for an empty slice.
pub fn sum_rust(values: &[f64]) -> f64 {
    let s = values.iter().sum::<f64>();
    log::debug!("sum_rust({} values) = {}", values.len(), s);
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mean_rust_basic() {
        assert!((mean_rust(&[1.0, 2.0, 3.0, 4.0, 5.0]) - 3.0).abs() < 1e-9);
    }

    #[test]
    fn sum_rust_basic() {
        assert_eq!(sum_rust(&[1.0, 2.0, 3.0]), 6.0);
    }

    #[test]
    fn mean_rust_empty() {
        assert_eq!(mean_rust(&[]), 0.0);
    }
}
