// cpp/las_loader.cc — C++ LAS loader for the CloudCompare Rust sandbox
//
// Loads a .las file via CCCoreLib::FileIOFilter and exposes the point data
// to Rust through the CXX bridge. This is the ONLY C++ in the sandbox.
//
// Qt-free: uses only CCCoreLib and qCC_io static libs.
// The FileIOFilter::Open() call is the same code path used by CloudCompare
// when you File → Open a .las file in the GUI.
//
// Key insight: FileIOFilter returns a ccHObject* tree (generic object tree).
// We traverse it to find ccPointCloud children and extract the point data.

#include <cstdio>
#include <cstring>
#include <vector>
#include <string>
#include <stdexcept>

// CCCoreLib / qCC_io headers
#include "FileIOFilter.h"
#include "ccHObject.h"
#include "ccPointCloud.h"
#include "ccLog.h"

// CXX bridge header (generated by cxx-build from src/lib.rs)
#include "rust/cxx.h"

namespace sandbox {

struct LoadResult {
    std::vector<float> points;   // interleaved xyz: x0,y0,z0,x1,y1,z1,...
    size_t count = 0;
    bool has_colors = false;
    bool has_intensity = false;
    std::string error;
};

static LoadResult load_las_internal(const std::string& path) {
    LoadResult result;

    // Silencing ccLog for the sandbox (reduces noise)
    // In a real sandbox you might redirect ccLog to a file
    // ccLog::EnableStdLogging(false);

    // FileIOFilter::Open() reads the file and returns a ccHObject tree.
    // This is the same entry point as the CloudCompare GUI uses.
    ccHObject* container = FileIOFilter::Open(path);

    if (!container) {
        result.error = "FileIOFilter::Open() returned nullptr for: " + path;
        return result;
    }

    // Collect all ccPointCloud children from the loaded tree
    ccHObject::Container clouds;
    container->filterChildren(clouds, true, "PointCloud");

    if (clouds.empty()) {
        result.error = "No point cloud found in file: " + path;
        delete container;
        return result;
    }

    // Use the first cloud (most LAS files have exactly one cloud)
    ccPointCloud* cloud = static_cast<ccPointCloud*>(clouds[0]);
    size_t n = cloud->size();

    if (n == 0) {
        result.error = "Point cloud is empty: " + path;
        delete container;
        return result;
    }

    result.count = n;
    result.has_colors = cloud->hasColors();
    result.has_intensity = (cloud->getCurrentInScalarField() != nullptr);

    // Extract xyz into interleaved float buffer
    result.points.resize(n * 3);
    for (size_t i = 0; i < n; ++i) {
        const CCVector3* p = cloud->getPoint(i);
        result.points[i * 3 + 0] = static_cast<float>(p->x);
        result.points[i * 3 + 1] = static_cast<float>(p->y);
        result.points[i * 3 + 2] = static_cast<float>(p->z);
    }

    // Log summary to stderr (visible in cargo run output)
    fprintf(stderr, "[sandbox] Loaded %zu points from %s\n", n, path.c_str());
    if (result.has_colors)   fprintf(stderr, "[sandbox]   → has colors\n");
    if (result.has_intensity) fprintf(stderr, "[sandbox]   → has intensity\n");

    delete container;
    return result;
}

}  // namespace sandbox

// ── CXX bridge ────────────────────────────────────────────────────────────
// These functions are called from Rust via the cxx::bridge in src/lib.rs

::sandbox::LoadResult sandbox_load_las(const ::std::string& path) {
    return ::sandbox::load_las_internal(path);
}

size_t sandbox_cloud_point_count(const ::sandbox::LoadResult& result) {
    return result.count;
}
